/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {
    blockquote: BlockquoteBlock;
    heroParallax: HeroParallaxBlock;
    ingress: IngressBlock;
    richText: RichTextBlock;
    richTextWithHeading: RichTextWithHeadingBlock;
    imageGallery: ImageGalleryBlock;
    dealsCarousel: DealsCarouselBlock;
  };
  collections: {
    blog: Blog;
    'color-recommendations': ColorRecommendation;
    deals: Deal;
    events: Event;
    media: Media;
    pages: Page;
    restaurants: Restaurant;
    'shopping-queries': ShoppingQuery;
    stores: Store;
    tags: Tag;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    blog: BlogSelect<false> | BlogSelect<true>;
    'color-recommendations': ColorRecommendationsSelect<false> | ColorRecommendationsSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    restaurants: RestaurantsSelect<false> | RestaurantsSelect<true>;
    'shopping-queries': ShoppingQueriesSelect<false> | ShoppingQueriesSelect<true>;
    stores: StoresSelect<false> | StoresSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'sv';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockquoteBlock".
 */
export interface BlockquoteBlock {
  /**
   * Quote text
   */
  quote: string;
  /**
   * Quote author/attribution (e.g., "Butikschefen", "Store Manager")
   */
  author?: string | null;
  /**
   * Color variant for the section background
   */
  colorVariant?:
    | (
        | 'default'
        | 'subdued'
        | 'contrast'
        | 'primary.subdued'
        | 'primary.tonal'
        | 'primary.vibrant'
        | 'primary.contrast'
        | 'secondary.subdued'
        | 'secondary.tonal'
        | 'secondary.vibrant'
        | 'secondary.contrast'
        | 'tertiary.subdued'
        | 'tertiary.tonal'
        | 'tertiary.vibrant'
        | 'tertiary.contrast'
        | 'navbar.top'
        | 'navbar.base'
        | 'campaign'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'blockquote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroParallaxBlock".
 */
export interface HeroParallaxBlock {
  /**
   * Main heading text (uppercase)
   */
  headingUpper: string;
  /**
   * Secondary heading text (serif font)
   */
  headingLower: string;
  /**
   * Hero description text
   */
  description: string;
  /**
   * Hero image with parallax effect (optional, defaults to placeholder)
   */
  imageUrl?: (string | null) | Media;
  /**
   * Display opening hours badges (automatically calculated from current time)
   */
  showOpeningHours?: boolean | null;
  /**
   * Location ID for opening hours (future: will fetch from collection)
   */
  locationId?: string | null;
  /**
   * Quick navigation buttons (leave empty for default links)
   */
  quickLinks?:
    | {
        label: string;
        icon: 'compass' | 'shopping' | 'food' | 'confetti';
        /**
         * Link URL
         */
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Text for diagonal scrolling marquee
   */
  marqueeText?: string | null;
  /**
   * Color variant for the section background
   */
  colorVariant?:
    | (
        | 'default'
        | 'subdued'
        | 'contrast'
        | 'primary.subdued'
        | 'primary.tonal'
        | 'primary.vibrant'
        | 'primary.contrast'
        | 'secondary.subdued'
        | 'secondary.tonal'
        | 'secondary.vibrant'
        | 'secondary.contrast'
        | 'tertiary.subdued'
        | 'tertiary.tonal'
        | 'tertiary.vibrant'
        | 'tertiary.contrast'
        | 'navbar.top'
        | 'navbar.base'
        | 'campaign'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroParallax';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * This will be used as the display name for this asset
   */
  title: string;
  /**
   * Alternative text for accessibility and SEO
   */
  alt: string;
  /**
   * Detailed description of the asset
   */
  description?: string | null;
  /**
   * Whether this asset is publicly accessible
   */
  isPublic?: boolean | null;
  /**
   * Mark as featured asset
   */
  isFeatured?: boolean | null;
  /**
   * Copyright information
   */
  copyright?: string | null;
  license?:
    | ('all-rights-reserved' | 'cc-by' | 'cc-by-sa' | 'cc-by-nc' | 'cc-by-nc-sa' | 'public-domain' | 'custom')
    | null;
  /**
   * Enter custom license terms
   */
  customLicense?: string | null;
  metadata?: {
    camera?: string | null;
    lens?: string | null;
    settings?: {
      iso?: number | null;
      aperture?: string | null;
      shutterSpeed?: string | null;
      focalLength?: string | null;
    };
    location?: {
      name?: string | null;
      latitude?: number | null;
      longitude?: number | null;
    };
  };
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IngressBlock".
 */
export interface IngressBlock {
  /**
   * Main heading
   */
  heading: string;
  /**
   * Introduction text (simple text, supports line breaks)
   */
  content: string;
  /**
   * Color variant for the section background
   */
  colorVariant?:
    | (
        | 'default'
        | 'subdued'
        | 'contrast'
        | 'primary.subdued'
        | 'primary.tonal'
        | 'primary.vibrant'
        | 'primary.contrast'
        | 'secondary.subdued'
        | 'secondary.tonal'
        | 'secondary.vibrant'
        | 'secondary.contrast'
        | 'tertiary.subdued'
        | 'tertiary.tonal'
        | 'tertiary.vibrant'
        | 'tertiary.contrast'
        | 'navbar.top'
        | 'navbar.base'
        | 'campaign'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ingress';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock".
 */
export interface RichTextBlock {
  /**
   * Rich text content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Number of columns for text layout
   */
  columns?: ('1' | '2') | null;
  /**
   * Color variant for the section background
   */
  colorVariant?:
    | (
        | 'default'
        | 'subdued'
        | 'contrast'
        | 'primary.subdued'
        | 'primary.tonal'
        | 'primary.vibrant'
        | 'primary.contrast'
        | 'secondary.subdued'
        | 'secondary.tonal'
        | 'secondary.vibrant'
        | 'secondary.contrast'
        | 'tertiary.subdued'
        | 'tertiary.tonal'
        | 'tertiary.vibrant'
        | 'tertiary.contrast'
        | 'navbar.top'
        | 'navbar.base'
        | 'campaign'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextWithHeadingBlock".
 */
export interface RichTextWithHeadingBlock {
  /**
   * Section heading
   */
  heading: string;
  /**
   * Rich text content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Number of columns for text layout
   */
  columns?: ('1' | '2') | null;
  /**
   * Color variant for the section background
   */
  colorVariant?:
    | (
        | 'default'
        | 'subdued'
        | 'contrast'
        | 'primary.subdued'
        | 'primary.tonal'
        | 'primary.vibrant'
        | 'primary.contrast'
        | 'secondary.subdued'
        | 'secondary.tonal'
        | 'secondary.vibrant'
        | 'secondary.contrast'
        | 'tertiary.subdued'
        | 'tertiary.tonal'
        | 'tertiary.vibrant'
        | 'tertiary.contrast'
        | 'navbar.top'
        | 'navbar.base'
        | 'campaign'
      )
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'richTextWithHeading';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock".
 */
export interface ImageGalleryBlock {
  /**
   * Optional gallery title
   */
  title?: string | null;
  images: {
    image: string | Media;
    /**
     * Alt text for accessibility
     */
    alt?: string | null;
    /**
     * Optional image caption
     */
    caption?: string | null;
    id?: string | null;
  }[];
  /**
   * Display layout for the gallery
   */
  layout?: ('carousel' | 'grid' | 'masonry') | null;
  /**
   * Show navigation arrows for carousel
   */
  showNavigation?: boolean | null;
  /**
   * Show dot indicators for carousel
   */
  showDots?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'imageGallery';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DealsCarouselBlock".
 */
export interface DealsCarouselBlock {
  /**
   * Section title (optional - defaults to "Våra deals")
   */
  title?: string | null;
  /**
   * Only show active deals
   */
  showOnlyActive?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'dealsCarousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title: string;
  slug: string;
  /**
   * Author name
   */
  author?: string | null;
  /**
   * Publication date and time
   */
  publishedDate: string;
  /**
   * Main blog post image (optional - can be added later)
   */
  heroImage?: (string | null) | Media;
  /**
   * Tags for categorizing the blog post
   */
  tags?: (string | Tag)[] | null;
  content: {
    /**
     * Short excerpt for listing pages and SEO
     */
    excerpt: string;
    /**
     * Full blog post content
     */
    body: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Additional images for the blog post
     */
    gallery?:
      | {
          image: string | Media;
          /**
           * Image caption (optional)
           */
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  relationships?: {
    /**
     * Related blog posts
     */
    relatedPosts?: (string | Blog)[] | null;
  };
  /**
   * SEO meta title (defaults to post title)
   */
  metaTitle?: string | null;
  /**
   * SEO meta description (defaults to excerpt)
   */
  metaDescription?: string | null;
  /**
   * SEO/social media image (defaults to hero image)
   */
  metaImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name: string;
  slug: string;
  /**
   * Determines where this tag can be used
   */
  category: 'store' | 'restaurant' | 'both';
  color: 'red' | 'blue' | 'green' | 'yellow' | 'purple' | 'orange' | 'pink' | 'gray';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-recommendations".
 */
export interface ColorRecommendation {
  id: string;
  /**
   * User identifier (optional)
   */
  userId?: string | null;
  /**
   * Original uploaded photo for analysis
   */
  uploadedPhoto: string | Media;
  /**
   * Detected skin tone from AI analysis
   */
  skinTone: string;
  /**
   * Detected hair color (optional)
   */
  hairColor?: string | null;
  /**
   * Detected eye color (optional)
   */
  eyeColor?: string | null;
  recommendations: {
    colors?:
      | {
          /**
           * Color name (e.g., "Emerald Green", "Soft Beige")
           */
          name: string;
          /**
           * Hex color code (e.g., #50C878)
           */
          hex: string;
          /**
           * Category for this color
           */
          category: 'clothing' | 'accessories' | 'makeup' | 'general';
          /**
           * Why this color works for the person
           */
          reasoning?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Overall reasoning for the color palette
     */
    reasoning: string;
    /**
     * Seasonal color analysis result
     */
    seasonalAnalysis: 'warm' | 'cool' | 'neutral' | 'warm-neutral' | 'cool-neutral';
    /**
     * Current fashion trends that influenced recommendations
     */
    trends?:
      | {
          trend: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Complete outfit recommendations with styling tips
     */
    outfits?:
      | {
          name: string;
          occasion: string;
          season: string;
          styling: string;
          confidence: number;
          generatedImageUrl?: string | null;
          items?:
            | {
                name: string;
                type: 'top' | 'bottom' | 'dress' | 'outerwear' | 'shoes' | 'accessories';
                color: string;
                hex: string;
                description: string;
                styling?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * AI-generated visualization of color recommendations
   */
  generatedImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: string;
  /**
   * Deal title (e.g., "25% off on beauty products")
   */
  title: string;
  /**
   * Short description of the deal
   */
  description?: string | null;
  /**
   * Deal image (recommended: 400x480px)
   */
  image?: (string | null) | Media;
  /**
   * Stores where this deal is available
   */
  stores?: (string | Store)[] | null;
  /**
   * Restaurants where this deal is available
   */
  restaurants?: (string | Restaurant)[] | null;
  /**
   * Badges to display on the deal card (e.g., "25% OFF")
   */
  badges?:
    | {
        label: string;
        colorVariant?:
          | (
              | 'default'
              | 'subdued'
              | 'contrast'
              | 'primary.subdued'
              | 'primary.tonal'
              | 'primary.vibrant'
              | 'primary.contrast'
              | 'secondary.subdued'
              | 'secondary.tonal'
              | 'secondary.vibrant'
              | 'secondary.contrast'
              | 'tertiary.subdued'
              | 'tertiary.tonal'
              | 'tertiary.vibrant'
              | 'tertiary.contrast'
              | 'navbar.top'
              | 'navbar.base'
              | 'campaign'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Whether this deal is currently active
   */
  isActive?: boolean | null;
  /**
   * When the deal becomes active
   */
  validFrom?: string | null;
  /**
   * When the deal expires
   */
  validUntil?: string | null;
  link?: {
    /**
     * External link (e.g., to product page)
     */
    url?: string | null;
    /**
     * Link text (e.g., "Shop now")
     */
    label?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores".
 */
export interface Store {
  id: string;
  name: string;
  slug: string;
  /**
   * Check if this store is located outside the main shopping center
   */
  isExternal?: boolean | null;
  /**
   * Main store image for header
   */
  heroImage?: (string | null) | Media;
  /**
   * Store logo (SVG or PNG)
   */
  logo?: (string | null) | Media;
  /**
   * Tags for categorizing the store
   */
  tags?: (string | Tag)[] | null;
  /**
   * Active deals for this store
   */
  deals?: (string | Deal)[] | null;
  /**
   * Add content blocks to build your store page. The hero section is automatically generated from the store name and hero image.
   */
  contentBlocks?:
    | (
        | IngressBlock
        | RichTextBlock
        | RichTextWithHeadingBlock
        | BlockquoteBlock
        | ImageGalleryBlock
        | DealsCarouselBlock
      )[]
    | null;
  contact?: {
    /**
     * Phone number for "Ring oss" button
     */
    phoneNumber?: string | null;
    links?: {
      /**
       * Store website URL
       */
      website?: string | null;
      /**
       * Instagram profile URL
       */
      instagram?: string | null;
      /**
       * Facebook page URL
       */
      facebook?: string | null;
      /**
       * TikTok profile URL
       */
      tiktok?: string | null;
    };
    /**
     * Store address
     */
    address?: string | null;
    coordinates?: {
      /**
       * Latitude for map integration
       */
      lat?: number | null;
      /**
       * Longitude for map integration
       */
      lng?: number | null;
    };
  };
  businessData?: {
    /**
     * Price range indicator
     */
    priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
    /**
     * Comma-separated list of products sold (e.g., "pants, scarves, jackets") - AI metadata
     */
    productsSold?: string | null;
  };
  /**
   * SEO meta title
   */
  metaTitle?: string | null;
  /**
   * SEO meta description
   */
  metaDescription?: string | null;
  /**
   * SEO/social media image
   */
  metaImage?: (string | null) | Media;
  /**
   * Select related stores, events, or restaurants to display on this store page
   */
  relatedContent?:
    | (
        | {
            relationTo: 'stores';
            value: string | Store;
          }
        | {
            relationTo: 'events';
            value: string | Event;
          }
        | {
            relationTo: 'restaurants';
            value: string | Restaurant;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  name: string;
  slug: string;
  /**
   * Main event image for header
   */
  heroImage: string | Media;
  /**
   * Tags for categorizing the event
   */
  tags?: (string | Tag)[] | null;
  eventDetails: {
    /**
     * Event start date and time
     */
    startDate: string;
    /**
     * Event end date and time (optional)
     */
    endDate?: string | null;
    /**
     * Event location (e.g., "Main Square", "Conference Room A")
     */
    location?: string | null;
    /**
     * Event organizer name
     */
    organizer?: string | null;
    /**
     * Ticket price or "Free" if free entry
     */
    price?: string | null;
  };
  content: {
    /**
     * Additional event images
     */
    gallery?:
      | {
          image: string | Media;
          id?: string | null;
        }[]
      | null;
    /**
     * Full event description
     */
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    /**
     * Short excerpt for listing pages
     */
    excerpt?: string | null;
  };
  contact?: {
    /**
     * Contact email for inquiries
     */
    email?: string | null;
    /**
     * Contact phone number
     */
    phoneNumber?: string | null;
    /**
     * Event website or registration URL
     */
    website?: string | null;
  };
  relationships?: {
    /**
     * Related events
     */
    relatedEvents?: (string | Event)[] | null;
  };
  /**
   * SEO meta title
   */
  metaTitle?: string | null;
  /**
   * SEO meta description
   */
  metaDescription?: string | null;
  /**
   * SEO/social media image
   */
  metaImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants".
 */
export interface Restaurant {
  id: string;
  name: string;
  slug: string;
  /**
   * Check if this restaurant is located outside the main shopping center
   */
  isExternal?: boolean | null;
  /**
   * Main restaurant image for header
   */
  heroImage?: (string | null) | Media;
  /**
   * Restaurant logo (SVG or PNG)
   */
  logo?: (string | null) | Media;
  /**
   * Tags for categorizing the restaurant (e.g., cuisine types)
   */
  tags?: (string | Tag)[] | null;
  /**
   * Active deals for this restaurant
   */
  deals?: (string | Deal)[] | null;
  /**
   * Add content blocks to build your restaurant page. The hero section is automatically generated from the restaurant name and hero image.
   */
  contentBlocks?:
    | (
        | IngressBlock
        | RichTextBlock
        | RichTextWithHeadingBlock
        | BlockquoteBlock
        | ImageGalleryBlock
        | DealsCarouselBlock
      )[]
    | null;
  contact?: {
    /**
     * Phone number for "Ring oss" button
     */
    phoneNumber?: string | null;
    links?: {
      /**
       * Restaurant website URL
       */
      website?: string | null;
      /**
       * Instagram profile URL
       */
      instagram?: string | null;
      /**
       * Facebook page URL
       */
      facebook?: string | null;
      /**
       * TikTok profile URL
       */
      tiktok?: string | null;
    };
    /**
     * Restaurant address
     */
    address?: string | null;
    coordinates?: {
      /**
       * Latitude for map integration
       */
      lat?: number | null;
      /**
       * Longitude for map integration
       */
      lng?: number | null;
    };
  };
  businessData?: {
    /**
     * Menu file (PDF or image)
     */
    menu?: (string | null) | Media;
    /**
     * Price range indicator
     */
    priceRange?: ('$' | '$$' | '$$$' | '$$$$') | null;
    /**
     * Comma-separated list of dishes served (e.g., "pizza, pasta, salads") - AI metadata
     */
    dishesServed?: string | null;
    /**
     * Available dietary options (indicates availability, not exclusivity)
     */
    dietaryOptions?: ('vegetarian' | 'vegan' | 'gluten-free' | 'halal' | 'kosher' | 'dairy-free')[] | null;
  };
  /**
   * SEO meta title
   */
  metaTitle?: string | null;
  /**
   * SEO meta description
   */
  metaDescription?: string | null;
  /**
   * SEO/social media image
   */
  metaImage?: (string | null) | Media;
  /**
   * Select related stores, events, or restaurants to display on this restaurant page
   */
  relatedContent?:
    | (
        | {
            relationTo: 'stores';
            value: string | Store;
          }
        | {
            relationTo: 'events';
            value: string | Event;
          }
        | {
            relationTo: 'restaurants';
            value: string | Restaurant;
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  slug: string;
  /**
   * Build your page with content blocks. Start with a hero, add rich content sections, quotes, and image galleries.
   */
  content?:
    | (
        | HeroParallaxBlock
        | IngressBlock
        | RichTextBlock
        | RichTextWithHeadingBlock
        | BlockquoteBlock
        | ImageGalleryBlock
      )[]
    | null;
  meta?: {
    /**
     * SEO meta title
     */
    title?: string | null;
    /**
     * SEO meta description
     */
    description?: string | null;
    /**
     * SEO/social media image
     */
    image?: (string | null) | Media;
    /**
     * Canonical URL
     */
    canonical?: string | null;
    robots?: ('index, follow' | 'index, nofollow' | 'noindex, follow' | 'noindex, nofollow') | null;
  };
  publishedAt?: string | null;
  status?: ('draft' | 'published' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopping-queries".
 */
export interface ShoppingQuery {
  id: string;
  /**
   * The natural language search query
   */
  query: string;
  /**
   * Search filters applied
   */
  filters?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Number of venues returned
   */
  resultCount: number;
  /**
   * Agent reasoning for the search results
   */
  reasoning?: string | null;
  /**
   * User preferences if available
   */
  userPreferences?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Response time in milliseconds
   */
  responseTime: number;
  /**
   * When the query was executed
   */
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'color-recommendations';
        value: string | ColorRecommendation;
      } | null)
    | ({
        relationTo: 'deals';
        value: string | Deal;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'restaurants';
        value: string | Restaurant;
      } | null)
    | ({
        relationTo: 'shopping-queries';
        value: string | ShoppingQuery;
      } | null)
    | ({
        relationTo: 'stores';
        value: string | Store;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  publishedDate?: T;
  heroImage?: T;
  tags?: T;
  content?:
    | T
    | {
        excerpt?: T;
        body?: T;
        gallery?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
      };
  relationships?:
    | T
    | {
        relatedPosts?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "color-recommendations_select".
 */
export interface ColorRecommendationsSelect<T extends boolean = true> {
  userId?: T;
  uploadedPhoto?: T;
  skinTone?: T;
  hairColor?: T;
  eyeColor?: T;
  recommendations?:
    | T
    | {
        colors?:
          | T
          | {
              name?: T;
              hex?: T;
              category?: T;
              reasoning?: T;
              id?: T;
            };
        reasoning?: T;
        seasonalAnalysis?: T;
        trends?:
          | T
          | {
              trend?: T;
              id?: T;
            };
        outfits?:
          | T
          | {
              name?: T;
              occasion?: T;
              season?: T;
              styling?: T;
              confidence?: T;
              generatedImageUrl?: T;
              items?:
                | T
                | {
                    name?: T;
                    type?: T;
                    color?: T;
                    hex?: T;
                    description?: T;
                    styling?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  generatedImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  stores?: T;
  restaurants?: T;
  badges?:
    | T
    | {
        label?: T;
        colorVariant?: T;
        id?: T;
      };
  isActive?: T;
  validFrom?: T;
  validUntil?: T;
  link?:
    | T
    | {
        url?: T;
        label?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  tags?: T;
  eventDetails?:
    | T
    | {
        startDate?: T;
        endDate?: T;
        location?: T;
        organizer?: T;
        price?: T;
      };
  content?:
    | T
    | {
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
        description?: T;
        excerpt?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phoneNumber?: T;
        website?: T;
      };
  relationships?:
    | T
    | {
        relatedEvents?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  description?: T;
  isPublic?: T;
  isFeatured?: T;
  copyright?: T;
  license?: T;
  customLicense?: T;
  metadata?:
    | T
    | {
        camera?: T;
        lens?: T;
        settings?:
          | T
          | {
              iso?: T;
              aperture?: T;
              shutterSpeed?: T;
              focalLength?: T;
            };
        location?:
          | T
          | {
              name?: T;
              latitude?: T;
              longitude?: T;
            };
      };
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?:
    | T
    | {
        heroParallax?: T | HeroParallaxBlockSelect<T>;
        ingress?: T | IngressBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        richTextWithHeading?: T | RichTextWithHeadingBlockSelect<T>;
        blockquote?: T | BlockquoteBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        robots?: T;
      };
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroParallaxBlock_select".
 */
export interface HeroParallaxBlockSelect<T extends boolean = true> {
  headingUpper?: T;
  headingLower?: T;
  description?: T;
  imageUrl?: T;
  showOpeningHours?: T;
  locationId?: T;
  quickLinks?:
    | T
    | {
        label?: T;
        icon?: T;
        href?: T;
        id?: T;
      };
  marqueeText?: T;
  colorVariant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IngressBlock_select".
 */
export interface IngressBlockSelect<T extends boolean = true> {
  heading?: T;
  content?: T;
  colorVariant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextBlock_select".
 */
export interface RichTextBlockSelect<T extends boolean = true> {
  content?: T;
  columns?: T;
  colorVariant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RichTextWithHeadingBlock_select".
 */
export interface RichTextWithHeadingBlockSelect<T extends boolean = true> {
  heading?: T;
  content?: T;
  columns?: T;
  colorVariant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BlockquoteBlock_select".
 */
export interface BlockquoteBlockSelect<T extends boolean = true> {
  quote?: T;
  author?: T;
  colorVariant?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImageGalleryBlock_select".
 */
export interface ImageGalleryBlockSelect<T extends boolean = true> {
  title?: T;
  images?:
    | T
    | {
        image?: T;
        alt?: T;
        caption?: T;
        id?: T;
      };
  layout?: T;
  showNavigation?: T;
  showDots?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restaurants_select".
 */
export interface RestaurantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isExternal?: T;
  heroImage?: T;
  logo?: T;
  tags?: T;
  deals?: T;
  contentBlocks?:
    | T
    | {
        ingress?: T | IngressBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        richTextWithHeading?: T | RichTextWithHeadingBlockSelect<T>;
        blockquote?: T | BlockquoteBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
        dealsCarousel?: T | DealsCarouselBlockSelect<T>;
      };
  contact?:
    | T
    | {
        phoneNumber?: T;
        links?:
          | T
          | {
              website?: T;
              instagram?: T;
              facebook?: T;
              tiktok?: T;
            };
        address?: T;
        coordinates?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
      };
  businessData?:
    | T
    | {
        menu?: T;
        priceRange?: T;
        dishesServed?: T;
        dietaryOptions?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  relatedContent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DealsCarouselBlock_select".
 */
export interface DealsCarouselBlockSelect<T extends boolean = true> {
  title?: T;
  showOnlyActive?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shopping-queries_select".
 */
export interface ShoppingQueriesSelect<T extends boolean = true> {
  query?: T;
  filters?: T;
  resultCount?: T;
  reasoning?: T;
  userPreferences?: T;
  responseTime?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stores_select".
 */
export interface StoresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  isExternal?: T;
  heroImage?: T;
  logo?: T;
  tags?: T;
  deals?: T;
  contentBlocks?:
    | T
    | {
        ingress?: T | IngressBlockSelect<T>;
        richText?: T | RichTextBlockSelect<T>;
        richTextWithHeading?: T | RichTextWithHeadingBlockSelect<T>;
        blockquote?: T | BlockquoteBlockSelect<T>;
        imageGallery?: T | ImageGalleryBlockSelect<T>;
        dealsCarousel?: T | DealsCarouselBlockSelect<T>;
      };
  contact?:
    | T
    | {
        phoneNumber?: T;
        links?:
          | T
          | {
              website?: T;
              instagram?: T;
              facebook?: T;
              tiktok?: T;
            };
        address?: T;
        coordinates?:
          | T
          | {
              lat?: T;
              lng?: T;
            };
      };
  businessData?:
    | T
    | {
        priceRange?: T;
        productsSold?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  metaImage?: T;
  relatedContent?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  color?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}